# Generated by Django 2.0.7 on 2018-11-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ajayidhikrullahscrumy', '0004_auto_20181106_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ajayidhikrullahscrumy', to='ajayidhikrullahscrumy.GoalStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ajayidhikrullahscrumy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='goals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajayidhikrullahscrumy', to='ajayidhikrullahscrumy.ScrumyGoals'),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='time_of_action',
            field=models.CharField(max_length=100),
        ),
    ]
