# Generated by Django 2.0.7 on 2018-11-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajayidhikrullahscrumy', '0003_auto_20181105_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumyhistory',
            old_name='Scrumygoals',
            new_name='goals',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='user',
        ),
    ]
